# Generated by Django 2.0.6 on 2018-10-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default='', null=True, verbose_name='url')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='title')),
                ('thumbnail', models.TextField(blank=True, default='', null=True, verbose_name='thumbnail')),
                ('keywords', models.TextField(blank=True, default='', null=True, verbose_name='keywords')),
                ('article', models.TextField(blank=True, default='', null=True, verbose_name='article')),
                ('article_source', models.TextField(blank=True, default='', null=True, verbose_name='article_url')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default='', null=True, verbose_name='url')),
                ('name', models.TextField(blank=True, default='', null=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='moretvtime.Category'),
        ),
    ]
