# Generated by Django 2.0.6 on 2018-10-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_source',
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.TextField(blank=True, default='', null=True, verbose_name='video'),
        ),
    ]
