# Generated by Django 2.0.6 on 2018-10-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0002_auto_20181014_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='article_html',
            field=models.TextField(blank=True, default='', null=True, verbose_name='article_html'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='article_text'),
        ),
    ]
