# Generated by Django 2.0.6 on 2018-10-14 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0003_auto_20181014_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('provider', models.TextField(blank=True, default='', null=True, verbose_name='provider')),
                ('sub_id', models.TextField(blank=True, default='', null=True, verbose_name='sub_id')),
                ('ip', models.TextField(blank=True, default='', null=True, verbose_name='ip')),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                ('sign', models.TextField(blank=True, default='', null=True, verbose_name='sign')),
            ],
        ),
    ]
