# Generated by Django 2.0.6 on 2018-10-16 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0004_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='last_view_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='views',
            field=models.IntegerField(default=0, verbose_name='views'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='views_limit',
            field=models.IntegerField(default=0, verbose_name='views_limit'),
        ),
    ]
