# Generated by Django 2.0.6 on 2018-10-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0005_auto_20181016_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='application',
            field=models.TextField(blank=True, default='', null=True, verbose_name='application'),
        ),
    ]
