# Generated by Django 2.0.6 on 2018-10-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0006_article_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='application',
            field=models.TextField(blank=True, default='', null=True, verbose_name='application'),
        ),
    ]
