# Generated by Django 2.0.6 on 2018-10-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0007_category_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='prev_sign',
            field=models.TextField(blank=True, default='', null=True, verbose_name='prev_sign'),
        ),
        migrations.AlterField(
            model_name='article',
            name='application',
            field=models.TextField(blank=True, choices=[('moretvtime', 'moretvtime.com'), ('youlovepranks', 'youlovepranks.com'), ('pranksforu', 'pranksforu.com'), ('funnypranks', 'funnypranks.me')], default='', null=True, verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='category',
            name='application',
            field=models.TextField(blank=True, choices=[('moretvtime', 'moretvtime.com'), ('youlovepranks', 'youlovepranks.com'), ('pranksforu', 'pranksforu.com'), ('funnypranks', 'funnypranks.me')], default='', null=True, verbose_name='application'),
        ),
    ]
