# Generated by Django 2.0.6 on 2018-10-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0008_auto_20181024_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSummary',
            fields=[
            ],
            options={
                'verbose_name': 'TrackingSummary',
                'verbose_name_plural': 'Tracking Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('moretvtime.tracking',),
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['sub_id', '-date'], name='moretvtime__sub_id_877007_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['ip', '-date'], name='moretvtime__ip_583604_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['sign', '-date'], name='moretvtime__sign_465d9d_idx'),
        ),
    ]
