# Generated by Django 2.0.6 on 2018-11-06 22:57

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0011_auto_20181104_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2, verbose_name='country'),
        ),
    ]
