# Generated by Django 2.0.6 on 2018-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0014_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
    ]
