# Generated by Django 2.0.6 on 2018-11-11 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0015_category_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='last_mc_view_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last_mc_view_date'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='last_view_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last_view_date'),
        ),
    ]
