# Generated by Django 2.0.6 on 2018-11-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0018_tracking_last_popunder_view_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='name')),
                ('code', models.TextField(default='', verbose_name='code')),
                ('is_static', models.BooleanField(default=False, verbose_name='is static banner')),
            ],
        ),
        migrations.CreateModel(
            name='BannerPlaceholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_number', models.IntegerField(default=1, verbose_name='paragraph number')),
                ('banners_above_button_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_above_button_1', to='moretvtime.Banner', verbose_name='banners above button 1')),
                ('banners_above_button_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_above_button_2', to='moretvtime.Banner', verbose_name='banners above button 2')),
                ('banners_below_button_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_below_button_1', to='moretvtime.Banner', verbose_name='banners below button 1')),
                ('banners_below_button_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_below_button_2', to='moretvtime.Banner', verbose_name='banners below button 2')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='name')),
                ('postback_url', models.TextField(default='', verbose_name='postback url')),
                ('views_limit', models.IntegerField(default=50, verbose_name='views limit')),
                ('postback_after_limit', models.BooleanField(default=False, verbose_name='do postback after limit')),
                ('impression_price', models.FloatField(blank=True, default=None, null=True, verbose_name='prev_sign')),
            ],
        ),
    ]
