# Generated by Django 2.0.6 on 2018-11-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0019_banner_bannerplaceholder_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerplaceholder',
            name='banners_above_button_1',
        ),
        migrations.RemoveField(
            model_name='bannerplaceholder',
            name='banners_above_button_2',
        ),
        migrations.RemoveField(
            model_name='bannerplaceholder',
            name='banners_below_button_1',
        ),
        migrations.RemoveField(
            model_name='bannerplaceholder',
            name='banners_below_button_2',
        ),
        migrations.AddField(
            model_name='bannerplaceholder',
            name='banner_above_button_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_above_button_1', to='moretvtime.Banner', verbose_name='banner above button 1'),
        ),
        migrations.AddField(
            model_name='bannerplaceholder',
            name='banner_above_button_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_above_button_2', to='moretvtime.Banner', verbose_name='banner above button 2'),
        ),
        migrations.AddField(
            model_name='bannerplaceholder',
            name='banner_below_button_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_below_button_1', to='moretvtime.Banner', verbose_name='banner below button 1'),
        ),
        migrations.AddField(
            model_name='bannerplaceholder',
            name='banner_below_button_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_below_button_2', to='moretvtime.Banner', verbose_name='banner below button 2'),
        ),
    ]
