# Generated by Django 2.0.6 on 2018-11-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0020_auto_20181121_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerplaceholder',
            name='banner_above_button_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_above_button_1', to='moretvtime.Banner', verbose_name='banner above button 1'),
        ),
        migrations.AlterField(
            model_name='bannerplaceholder',
            name='banner_above_button_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_above_button_2', to='moretvtime.Banner', verbose_name='banner above button 2'),
        ),
        migrations.AlterField(
            model_name='bannerplaceholder',
            name='banner_below_button_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_below_button_1', to='moretvtime.Banner', verbose_name='banner below button 1'),
        ),
        migrations.AlterField(
            model_name='bannerplaceholder',
            name='banner_below_button_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_below_button_2', to='moretvtime.Banner', verbose_name='banner below button 2'),
        ),
    ]
