# Generated by Django 2.0.6 on 2018-11-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0021_auto_20181121_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerplaceholder',
            name='timeout',
            field=models.IntegerField(default=10, verbose_name='timeout to wait'),
        ),
    ]
