# Generated by Django 2.0.6 on 2018-11-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0022_bannerplaceholder_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerplaceholder',
            name='selector',
            field=models.TextField(blank=True, default='', null=True, verbose_name='css selector'),
        ),
    ]
