# Generated by Django 2.0.6 on 2018-11-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0023_bannerplaceholder_selector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerplaceholder',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='bannerplaceholder',
            name='order',
            field=models.IntegerField(default=0, verbose_name='paragraph number'),
        ),
    ]
