# Generated by Django 2.0.6 on 2018-11-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0025_auto_20181121_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerplaceholder',
            name='insert_before',
            field=models.BooleanField(default=True, verbose_name='insert before article'),
        ),
    ]
