# Generated by Django 2.0.6 on 2018-11-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0026_bannerplaceholder_insert_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerplaceholder',
            name='insert_before',
            field=models.BooleanField(default=True, verbose_name='insert before paragraph'),
        ),
    ]
