# Generated by Django 2.0.6 on 2018-11-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0027_auto_20181122_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='autoremove',
            field=models.BooleanField(default=True, verbose_name='autoremove banner'),
        ),
    ]
