# Generated by Django 2.1.3 on 2018-12-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0031_auto_20181202_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerplaceholder',
            options={'ordering': ['is_test', 'order']},
        ),
    ]
