# Generated by Django 2.0.6 on 2018-12-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0034_auto_20181203_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='btc_paid',
            field=models.BooleanField(default=False, verbose_name='sent'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='btc_wallet',
            field=models.TextField(blank=True, default='', null=True, verbose_name='btc_wallet'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='captcha_solved',
            field=models.BooleanField(default=False, verbose_name='captcha_solved'),
        ),
    ]
