# Generated by Django 2.0.6 on 2018-12-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0035_auto_20181209_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='turn_views',
            field=models.IntegerField(default=1, verbose_name='turn_views'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='turn_views_limit',
            field=models.IntegerField(default=3, verbose_name='turn_views_limit'),
        ),
    ]
