# Generated by Django 2.0.6 on 2018-12-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0036_auto_20181220_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='turn_views',
            field=models.IntegerField(default=0, verbose_name='turn_views'),
        ),
    ]
