# Generated by Django 2.1.3 on 2018-12-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0037_auto_20181220_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(default='', verbose_name='ip')),
                ('is_vpn', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]