# Generated by Django 2.0.6 on 2018-12-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0038_vpn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='postback_after_limit',
            new_name='postback_after_all_impressions',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='views_limit',
        ),
        migrations.AddField(
            model_name='provider',
            name='impression_limit',
            field=models.IntegerField(default=50, verbose_name='impression limit'),
        ),
        migrations.AddField(
            model_name='provider',
            name='views_per_impression',
            field=models.IntegerField(default=3, verbose_name='views per impression'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='impression_price',
            field=models.FloatField(blank=True, default=0.001, null=True, verbose_name='impression price'),
        ),
    ]