# Generated by Django 2.0.6 on 2018-12-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0039_auto_20181225_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='postback_url',
            field=models.TextField(default='', help_text='Possible variables: {sub_id}, {ip}, {country}, {id}, {sign}, {compaign}, {price}', verbose_name='postback url'),
        ),
    ]