# Generated by Django 2.0.6 on 2019-01-09 22:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0040_auto_20181225_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField(default='', verbose_name='price')),
                ('country', django_countries.fields.CountryField(default='', max_length=2, verbose_name='country')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faucethub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_id', models.TextField(default='', verbose_name='payout_id')),
                ('payout_user_hash', models.TextField(default='', verbose_name='payout_user_hash')),
                ('status', models.TextField(default='', verbose_name='status')),
                ('ip', models.TextField(default='', verbose_name='ip')),
                ('toaddress', models.TextField(default='', verbose_name='to')),
                ('amount', models.FloatField(default='', verbose_name='amount')),
                ('companyname', models.TextField(default='', verbose_name='companyname')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='title')),
                ('thumbnail', models.FileField(default='', upload_to='article_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='title')),
                ('pagerole', models.TextField(default='', verbose_name='pagerole')),
                ('description', djrichtextfield.models.RichTextField(blank=True, default='', null=True, verbose_name='description')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Santoshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='title')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.TextField(default='', verbose_name='companyname')),
                ('toaddress', models.TextField(default='', help_text='BTC Address', verbose_name='toaddress')),
                ('companyamount', models.FloatField(blank=True, default='', verbose_name='companyamount')),
                ('useramount', models.FloatField(default='', verbose_name='useramount')),
                ('compantoption', models.TextField(blank=True, choices=[('crypto-provider', 'crypto-provider'), ('crypto-advertising', 'crypto-advertising')], default='', null=True, verbose_name='compantoption')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=0, verbose_name='article_order'),
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='moretvtime.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_html',
            field=djrichtextfield.models.RichTextField(blank=True, default='', null=True, verbose_name='article_html'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=djrichtextfield.models.RichTextField(blank=True, default='', null=True, verbose_name='article_text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(default='', upload_to='article_images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=djrichtextfield.models.RichTextField(blank=True, default='', null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video_html',
            field=djrichtextfield.models.RichTextField(blank=True, default='', null=True, verbose_name='video html'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('url', 'parent')},
        ),
    ]
