# Generated by Django 2.0.6 on 2019-01-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0042_auto_20190112_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail_url',
            field=models.TextField(blank=True, default='', null=True, verbose_name='thumbnail_url'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postback_url',
            field=models.TextField(default='', help_text='Possible variables: {sub_id}, {ip}, {country}, {id}, {sign}, {compaign}, {price}, {extra1}, {extra2}, {extra3}', verbose_name='postback url'),
        ),
    ]
