# Generated by Django 2.0.6 on 2019-01-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0043_auto_20190113_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(default='')),
                ('uuid', models.TextField(default='')),
                ('value', models.TextField(default='')),
                ('solved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('solved_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
