# Generated by Django 2.0.6 on 2019-01-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0044_captcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='impression_limit',
            field=models.IntegerField(default=50, verbose_name='page limit'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='impression_price',
            field=models.FloatField(blank=True, default=0.001, null=True, verbose_name='cycle price'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='views_per_impression',
            field=models.IntegerField(default=3, verbose_name='pages per cycle'),
        ),
    ]
