# Generated by Django 2.0.6 on 2019-01-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0045_auto_20190114_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='extra4',
            field=models.TextField(blank=True, default='', null=True, verbose_name='extra4'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='extra5',
            field=models.TextField(blank=True, default='', null=True, verbose_name='extra5'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postback_url',
            field=models.TextField(default='', help_text='Possible variables: {sub_id}, {ip}, {country}, {id}, {sign}, {compaign}, {price}, {extra1}, {extra2}, {extra3}, {extra4}, {extra5}', verbose_name='postback url'),
        ),
    ]
