# Generated by Django 2.0 on 2019-01-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0047_auto_20190120_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='ip_limit',
            field=models.IntegerField(default=50, verbose_name='limit per ip'),
        ),
    ]
