# Generated by Django 2.0 on 2019-01-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0052_auto_20190127_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmoney',
            name='limit',
            field=models.TextField(default='', help_text='Article Limit', verbose_name='limit'),
        ),
    ]
