# Generated by Django 2.0 on 2019-01-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0053_sendmoney_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faucethub',
            options={'verbose_name': 'All Crypto Transaction'},
        ),
        migrations.AlterModelOptions(
            name='santoshi',
            options={'verbose_name': 'Santoshi Converter'},
        ),
        migrations.AlterModelOptions(
            name='sendmoney',
            options={'verbose_name': 'Add Crypto Company'},
        ),
    ]
