# Generated by Django 2.0 on 2019-02-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0054_auto_20190130_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='postback_url',
            field=models.TextField(blank=True, default='', help_text='Possible variables: {sub_id}, {ip}, {country}, {id}, {sign}, {compaign}, {price}, {extra1}, {extra2}, {extra3}, {extra4}, {extra5}', null=True, verbose_name='postback url'),
        ),
    ]
