# Generated by Django 2.0 on 2019-02-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0055_auto_20190204_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerplaceholder',
            name='application',
            field=models.TextField(choices=[('mtt_desktop', 'mtt_desktop'), ('mtt_mobile', 'mtt_mobile')], default='mtt_desktop', verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='bannerbutton',
            name='type',
            field=models.TextField(choices=[('button', 'button'), ('iframe', 'iframe'), ('redirect', 'redirect'), ('captcha', 'captcha'), ('autoscroll', 'autoscroll'), ('start', 'start'), ('final', 'final')], default='button', verbose_name='action type'),
        ),
        migrations.AlterField(
            model_name='sendmoney',
            name='toaddress',
            field=models.TextField(blank=True, default='', help_text='BTC Address', null=True, verbose_name='toaddress'),
        ),
    ]
