# Generated by Django 2.0 on 2019-02-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0056_auto_20190210_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(default='')),
                ('counter', models.IntegerField(default=0)),
                ('last_trigger_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
