# Generated by Django 2.0.6 on 2019-02-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0057_captchatrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_mobile',
            field=models.BooleanField(default=False, verbose_name='is mobile'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='autoremove',
            field=models.BooleanField(default=False, verbose_name='autoremove banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_static',
            field=models.BooleanField(default=False, verbose_name='is static'),
        ),
    ]
