# Generated by Django 2.0 on 2019-02-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0058_auto_20190220_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmoney',
            name='companyamount',
        ),
        migrations.RemoveField(
            model_name='sendmoney',
            name='useramount',
        ),
        migrations.AddField(
            model_name='sendmoney',
            name='company_amount',
            field=models.FloatField(default=0.0, null=True, verbose_name='company_amount'),
        ),
        migrations.AddField(
            model_name='sendmoney',
            name='user_amount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='user_amount'),
        ),
    ]
