# Generated by Django 2.0 on 2019-03-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0061_auto_20190227_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayLatterFaucetHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.TextField(default='', verbose_name='companyname')),
                ('sub_id', models.TextField(default='', verbose_name='sub_id')),
                ('ip', models.TextField(default='', verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'All Pay Latter Transaction',
            },
        ),
        migrations.AlterField(
            model_name='bannerplaceholder',
            name='application',
            field=models.TextField(choices=[('mtt_desktop', 'mtt_desktop'), ('mtt_mobile', 'mtt_mobile'), ('mtt_special_desktop', 'mtt_special_desktop'), ('mtt_special_mobile', 'mtt_special_mobile')], default='mtt_desktop', verbose_name='application'),
        ),
    ]
