# Generated by Django 2.0 on 2019-03-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0062_auto_20190304_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paylatterfaucethub',
            options={'verbose_name': 'All Pay Latter Facuet Hub'},
        ),
        migrations.AddField(
            model_name='paylatterfaucethub',
            name='sent',
            field=models.BooleanField(default=True, verbose_name='sent'),
        ),
    ]
