# Generated by Django 2.0 on 2019-03-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moretvtime', '0063_auto_20190305_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylatterfaucethub',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='sent'),
        ),
    ]
