# Generated by Django 2.0 on 2019-02-08 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='text')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='title')),
                ('pagerole', models.TextField(default='', verbose_name='pagerole')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.TextField(default='', verbose_name='total')),
                ('payment_status', models.TextField(choices=[('Waiting For Payment', 'Waiting For Payment'), ('Paid', 'Paid'), ('Payment Canceled', 'Payment Canceled'), ('In Progress', 'In Progress')], default='', verbose_name='payment_status')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='name')),
                ('webaddress', models.TextField(default='', verbose_name='webaddress')),
                ('websitelanguage', models.TextField(default='', verbose_name='websitelanguage')),
                ('websitetraffic', models.TextField(blank=True, default='', null=True, verbose_name='websitetraffic')),
                ('site_status', models.TextField(choices=[('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='', verbose_name='site_status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(default='', verbose_name='subject')),
                ('priority', models.TextField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent'), ('Immediate', 'Immediate')], default='', verbose_name='priority')),
                ('status', models.TextField(choices=[('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='', verbose_name='site_status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='name')),
                ('widgettitle', models.TextField(default='', verbose_name='widgettitle')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('subtype', models.TextField(blank=True, default='', null=True, verbose_name='subtype')),
                ('column', models.TextField(blank=True, default='', null=True, verbose_name='column')),
                ('rows', models.TextField(blank=True, default='', null=True, verbose_name='rows')),
                ('wid', models.TextField(blank=True, default='', null=True, verbose_name='subtype')),
                ('css', models.TextField(blank=True, default='', null=True, verbose_name='css')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.Site')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.Support'),
        ),
    ]
