# Generated by Django 2.0 on 2019-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('paymentthreshold', models.TextField(default='', verbose_name='paymentthreshold')),
                ('paypalemail', models.TextField(default='', verbose_name='paypalemail')),
                ('ewallet', models.TextField(default='', verbose_name='ewallet')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payoneer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('paymentthreshold', models.TextField(default='', verbose_name='paymentthreshold')),
                ('payeename', models.TextField(default='', verbose_name='payeename')),
                ('country', models.TextField(default='', verbose_name='country')),
                ('ewallet', models.TextField(default='', verbose_name='ewallet')),
                ('paypalemail', models.TextField(default='', verbose_name='paypalemail')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('currency', models.TextField(default='', verbose_name='currency')),
                ('country', models.TextField(default='', verbose_name='country')),
                ('paymentthreshold', models.TextField(default='', verbose_name='paymentthreshold')),
                ('payeename', models.TextField(default='', verbose_name='payeename')),
                ('paypalemail', models.TextField(default='', verbose_name='paypalemail')),
                ('payeeaddress', models.TextField(default='', verbose_name='payeeaddress')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webmoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('currency', models.TextField(default='', verbose_name='currency')),
                ('paymentthreshold', models.TextField(default='', verbose_name='paymentthreshold')),
                ('wmz', models.TextField(default='', verbose_name='wmz')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
