# Generated by Django 2.0 on 2019-02-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_epayment_payoneer_paypal_webmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypal',
            name='payeephone',
            field=models.TextField(default='', verbose_name='payeephone'),
        ),
    ]
