# Generated by Django 2.0 on 2019-02-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190209_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epayment',
            name='paypalemail',
        ),
        migrations.RemoveField(
            model_name='payoneer',
            name='ewallet',
        ),
    ]
