# Generated by Django 2.0 on 2019-02-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='totalmoney',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
