# Generated by Django 2.0 on 2019-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_revenue_totalmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='addedby',
            field=models.TextField(choices=[('Admin', 'Admin')], default='', verbose_name='addedby'),
        ),
    ]
