# Generated by Django 2.0.6 on 2019-02-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_message_addedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='addedby',
            field=models.TextField(choices=[('Admin', 'Admin'), ('User', 'User')], default='', verbose_name='addedby'),
        ),
    ]
