# Generated by Django 2.0.6 on 2019-02-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190220_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='user',
        ),
    ]
