# Generated by Django 2.0 on 2019-01-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20190121_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrercompany',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='referrercountry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='referrer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.CharField(max_length=255),
        ),
    ]
