# Generated by Django 2.0 on 2019-01-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20190129_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allvisitor',
            name='referrer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='allvisitor',
            name='url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='allvisitor',
            name='user_agent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='referrer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
