# Generated by Django 2.0 on 2019-02-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20190129_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrercompany',
            name='bannerloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referrercompany',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
