# Generated by Django 2.0.6 on 2019-02-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20190216_2157'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='allvisitor',
            index=models.Index(fields=['session_key', '-last_update'], name='tracking_al_session_29cf49_idx'),
        ),
        migrations.AddIndex(
            model_name='allvisitor',
            index=models.Index(fields=['ip_address', '-last_update'], name='tracking_al_ip_addr_be97dc_idx'),
        ),
    ]
